[tool.poetry]
name = "pdf2jpg"
version = "0.1.0"
description = ""
authors = ["Ramon Voges <r.voges@dnb.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
wand = "^0.6.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
